# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Hosting Web
    url: https://cpanel.asvhosting.com
  - name: Hosting Radio
    url: https://asvradiostream.asvstudios.tk
  - name: Hosting Video
    url: https://stream.video.asvstudios.tk

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.asvstudios.it
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: A.S.V. Studios Hosting
  introTitle: Status Service - A.S.V. Studios Hosting
  introMessage: Verifica lo stato di attività dei servizi offerti da A.S.V. Studios.
  navbar:
    - title: Status
      href: /
    - title: Web Site
      href: https://www.asvstudios.it

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
